name: 'alpacca-web'

version: '3'

services:
  nuxt:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: '${PORT:-3000}'
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    volumes:
      - .:/app
      - /app/node_modules
