export enum LANGUAGE {
    CS = 'cs',
    EN = 'en',
}

export enum ROLE {
    ADMIN = 'admin',
    USER = 'user',
}

export enum RESPONSE_CODE {
    SUCCESS = 'SUCCESS',
    CREATED = 'CREATED',
    CLIENT_ERROR = 'CLIENT_ERROR',
    TOKEN_MISMATCH = 'TOKEN_MISMATCH',
    EMAIL_VERIFICATION_NEEDED = 'EMAIL_VERIFICATION_NEEDED',
    UNAUTHORIZED = 'UNAUTHORIZED',
    TOKEN_MISSING = 'TOKEN_MISSING',
    TOKEN_CORRUPTED = 'TOKEN_CORRUPTED',
    TOKEN_INVALID = 'TOKEN_INVALID',
    GUEST_ONLY = 'GUEST_ONLY',
    UNAUTHENTICATED = 'UNAUTHENTICATED',
    NOT_FOUND = 'NOT_FOUND',
    METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
    INVALID_CONTENT = 'INVALID_CONTENT',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INVITATION_EXISTS = 'INVITATION_EXISTS',
    INVITATION_USER_EXISTS = 'INVITATION_USER_EXISTS',
    TOO_MANY_ATTEMPTS = 'TOO_MANY_ATTEMPTS',
    REGISTRATION_ALREADY_REQUESTED = 'REGISTRATION_ALREADY_REQUESTED',
    RESET_ALREADY_REQUESTED = 'RESET_ALREADY_REQUESTED',
    SERVER_ERROR = 'SERVER_ERROR',
}

export enum FILE_TYPE {
    TEMP = 'temp',
}

export enum GRID {
    CANDIDATE = 'candidate',
    COMPANY_INVITATION = 'company-invitation',
    COMPANY_USER = 'company-user',
}

export enum ORDER {
    ASC = 'asc',
    DESC = 'desc'
}